name: Push Stage version to DockerHub
on:
  push:
    branches:
      - 'dev'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Cut commit sha
        id: cut
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        
      - name: Log into DockerHUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCHUB_USERNAME }}
          password: ${{ secrets.DOCHUB_TOKEN }}
          
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ format('{0}/var_keeper:{1}', secrets.DOCHUB_USERNAME, steps.cut.outputs.sha_short) }}
            ${{ format('{0}/var_keeper:latest', secrets.DOCHUB_USERNAME) }}
